{
 "title": "VallTourismInstaDashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter1", "label": "Filter 1" }
  ]
 },
 "panels": [
  {
   "title": "Number of posts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "id" }
   ]
  },
  {
   "title": "Number of faces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "id" }
   ]
  },
  {
   "title": "Posts",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "targets": [
    { "target": "id" },
    { "target": "faceIndex" },
    { "target": "shortCode" },
    { "target": "confidence" },
    { "target": "ageLow" },
    { "target": "ageHigh" },
    { "target": "gender" }
   ]
  },
  {
   "title": "Posts per time unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "id" }
   ]
  },
  {
   "title": "Gender",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "gender" },
    {}
   ]
  },
  {
   "title": "Average Emotion Confidence",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "fearConfidence" },
    { "target": "surprisedConfidence" },
    { "target": "angryConfidence" },
    { "target": "sadConfidence" },
    { "target": "happyConfidence" },
    { "target": "calmConfidence" },
    { "target": "disgustedConfidence" },
    { "target": "confusedConfidence" }
   ]
  },
  {
   "title": "Likes and Comments evolution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "likesCount" },
    { "target": "commentsCount" }
   ]
  },
  {
   "title": "Emotion per post",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 8 },
   "targets": [
    { "target": "fearConfidence" },
    { "target": "surprisedConfidence" },
    { "target": "angryConfidence" },
    { "target": "sadConfidence" },
    { "target": "happyConfidence" },
    { "target": "calmConfidence" },
    { "target": "disgustedConfidence" },
    { "target": "confusedConfidence" }
   ]
  }
 ]
}